In [24]:
import pandas as pd
import numpy as np

In [28]:
data = pd.read_csv("crop.csv")
del data["Unnamed: 0"]
del data["District_Name"]
del data["Crop_Year"]
data

State_Name  Season  Crop     Area  Production  Rainfall
0               0       1     2   1254.0      2000.0    1208.4
1               0       1    74      2.0         1.0    1208.4
2               0       1    95    102.0       321.0    1208.4
3               0       4     7    176.0       641.0    2763.2
4               0       4    22    720.0       165.0    2763.2
...           ...     ...   ...      ...         ...       ...
20032           3       2    41    282.0        89.0     182.6
20033           3       2    57    771.0       336.0     182.6
20034           3       2    69   8280.0      4683.0     182.6
20035           3       2    92  15849.0      7792.0     182.6
20036           3       2   119   6790.0      6675.0     182.6

[20037 rows x 6 columns]

In [29]:
data.isnull().sum()

State_Name     0
Season         0
Crop           0
Area           0
Production    73
Rainfall       0
dtype: int64

In [30]:
data = data.dropna(how="any", axis=0)
data

State_Name  Season  Crop     Area  Production  Rainfall
0               0       1     2   1254.0      2000.0    1208.4
1               0       1    74      2.0         1.0    1208.4
2               0       1    95    102.0       321.0    1208.4
3               0       4     7    176.0       641.0    2763.2
4               0       4    22    720.0       165.0    2763.2
...           ...     ...   ...      ...         ...       ...
20032           3       2    41    282.0        89.0     182.6
20033           3       2    57    771.0       336.0     182.6
20034           3       2    69   8280.0      4683.0     182.6
20035           3       2    92  15849.0      7792.0     182.6
20036           3       2   119   6790.0      6675.0     182.6

[19964 rows x 6 columns]

In [31]:
data.isnull().sum()

State_Name    0
Season        0
Crop          0
Area          0
Production    0
Rainfall      0
dtype: int64

In [32]:
x = data.iloc[:,:-2]
x
y = data.iloc[:,-1]
x["Rainfall"] = y
x

State_Name  Season  Crop     Area  Rainfall
0               0       1     2   1254.0    1208.4
1               0       1    74      2.0    1208.4
2               0       1    95    102.0    1208.4
3               0       4     7    176.0    2763.2
4               0       4    22    720.0    2763.2
...           ...     ...   ...      ...       ...
20032           3       2    41    282.0     182.6
20033           3       2    57    771.0     182.6
20034           3       2    69   8280.0     182.6
20035           3       2    92  15849.0     182.6
20036           3       2   119   6790.0     182.6

[19964 rows x 5 columns]

In [33]:
print(data.Crop.unique())

[  2  74  95   7  22  28  38 106 108 109  15  37 123 114  59  63 116   3
  43 107   6  25  33  45  48  53  90 111  41 119  61 102  57  98  67 122
  99 103  32  87  69 105  10  13  18  27  35  42  60  68 121  73  75  77
  85 112  62  34  55  86 101  19  92  80  65  17 117  39  40  66  88  49
  81  16  76  83]


In [34]:
y = data.iloc[:,-2]
y

0        2000.0
1           1.0
2         321.0
3         641.0
4         165.0
          ...  
20032      89.0
20033     336.0
20034    4683.0
20035    7792.0
20036    6675.0
Name: Production, Length: 19964, dtype: float64

In [35]:
x

State_Name  Season  Crop     Area  Rainfall
0               0       1     2   1254.0    1208.4
1               0       1    74      2.0    1208.4
2               0       1    95    102.0    1208.4
3               0       4     7    176.0    2763.2
4               0       4    22    720.0    2763.2
...           ...     ...   ...      ...       ...
20032           3       2    41    282.0     182.6
20033           3       2    57    771.0     182.6
20034           3       2    69   8280.0     182.6
20035           3       2    92  15849.0     182.6
20036           3       2   119   6790.0     182.6

[19964 rows x 5 columns]

In [36]:
y

0        2000.0
1           1.0
2         321.0
3         641.0
4         165.0
          ...  
20032      89.0
20033     336.0
20034    4683.0
20035    7792.0
20036    6675.0
Name: Production, Length: 19964, dtype: float64

In [37]:
X = x.values
X

array([[0.0000e+00, 1.0000e+00, 2.0000e+00, 1.2540e+03, 1.2084e+03],
       [0.0000e+00, 1.0000e+00, 7.4000e+01, 2.0000e+00, 1.2084e+03],
       [0.0000e+00, 1.0000e+00, 9.5000e+01, 1.0200e+02, 1.2084e+03],
       ...,
       [3.0000e+00, 2.0000e+00, 6.9000e+01, 8.2800e+03, 1.8260e+02],
       [3.0000e+00, 2.0000e+00, 9.2000e+01, 1.5849e+04, 1.8260e+02],
       [3.0000e+00, 2.0000e+00, 1.1900e+02, 6.7900e+03, 1.8260e+02]])

In [38]:
Y = y.values
Y

array([2.000e+03, 1.000e+00, 3.210e+02, ..., 4.683e+03, 7.792e+03,
       6.675e+03])

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,random_state=1,test_size=0.25)

In [40]:
X_train

array([[1.0000e+00, 4.0000e+00, 6.8000e+01, 1.3767e+04, 1.3184e+03],
       [3.0000e+00, 4.0000e+00, 2.8000e+01, 1.0700e+03, 2.4341e+03],
       [2.0000e+00, 1.0000e+00, 5.9000e+01, 1.4510e+03, 1.4150e+03],
       ...,
       [1.0000e+00, 2.0000e+00, 9.8000e+01, 7.1300e+02, 4.7140e+02],
       [2.0000e+00, 2.0000e+00, 1.1900e+02, 9.0000e+01, 4.4570e+02],
       [1.0000e+00, 1.0000e+00, 4.5000e+01, 2.3000e+03, 1.5402e+03]])

In [49]:
# RANDOM FOREST REGRESSOR
from sklearn.ensemble import RandomForestRegressor   

# TRAINING
model_rr = RandomForestRegressor(n_estimators = 10000,random_state = 0)
model_rr.fit(X_train, y_train)

# TESTING
rr_prediction = model_rr.predict(X_test)

In [50]:
from sklearn.metrics import r2_score
r2_score(y_test, rr_prediction)

0.7707198696334583

In [51]:
rr_prediction

array([4.29931839e+01, 2.78651133e+00, 6.34269300e+02, ...,
       5.32954774e+04, 2.04740000e+00, 1.08402203e+03])

In [52]:
model_rr.predict([[0,1,2,1254.0,1208.4]])[0]

1994.4933316666636

In [22]:
import pickle

In [ ]:
pickle.dump(model_rr, open("yieldcheck2.pkl", "wb"))
print("Saved All Models")